clc;clear;
start=questdlg('Do you want to play a game?','game','yes','no','no');
if ~(strcmpi(start,'yes'))
    error('gameover')
else
    list={'1','2','3','4','5'};
    number=randi([1,5]);
    prompt='Pick a number between 1 and 5';
    guess=listdlg('PromptString',prompt,'SelectionMode','single','listsize',[160,100],'ListString',list);
    if isempty(guess)
        error('gameover')       
    elseif number==guess
        fprintf('Good Job!')
    else
        fprintf('WRONG!')
        pause(2)
        clc
        fprintf('                          ...----....\n')
pause(.05)
fprintf('                    ..-:"''''         ''''"-..\n')
pause(.05)
fprintf('                 .-''                      ''-.\n')
pause(.05)
fprintf('               .''              .     .       ''.\n')
pause(.05)
fprintf('             .''   .          .    .      .    .''''.\n')
pause(.05)
fprintf('           .''  .    .       .   .   .     .   . ..:.\n')
pause(.05)
fprintf('         .'' .   . .  .       .   .   ..  .   . ....::.\n')
pause(.05)
fprintf('        ..   .   .      .  .    .     .  ..  . ....:IA.\n')
pause(.05)
fprintf('       .:  .   .    .    .  .  .    .. .  .. .. ....:IA.\n')
pause(.05)
fprintf('      .: .   .   ..   .    .     . . .. . ... ....:.:VHA.\n')
pause(.05)
fprintf('      ''..  .  .. .   .       .  . .. . .. . .....:.::IHHB.\n')
pause(.05)
fprintf('     .:. .  . .  . .   .  .  . . . ...:.:... .......:HIHMM.\n')
pause(.05)
fprintf('    .:.... .   . ."::"''.. .   .  . .:.:.:II;,. .. ..:IHIMMA\n')
pause(.05)
fprintf('    '':.:..  ..::IHHHHHI::. . .  ...:.::::.,,,. . ....VIMMHM\n')
pause(.05)
fprintf('   .:::I. .AHHHHHHHHHHAI::. .:...,:IIHHHHHHMMMHHL:. . VMMMM\n')
pause(.05)
fprintf('  .:.:V.:IVHHHHHHHMHMHHH::..:" .:HIHHHHHHHHHHHHHMHHA. .VMMM.\n')
pause(.05)
fprintf('  :..V.:IVHHHHHMMHHHHHHHB... . .:VPHHMHHHMMHHHHHHHHHAI.:VMMI\n')
pause(.05)
fprintf('  ::V..:VIHHHHHHMMMHHHHHH. .   .I":IIMHHMMHHHHHHHHHHHAPI:WMM\n')
pause(.05)
fprintf('  ::". .:.HHHHHHHHMMHHHHHI.  . .:..I:MHMMHHHHHHHHHMHV:'':H:WM\n')
pause(.05)
fprintf('  :: . :.::IIHHHHHHMMHHHHV  .ABA.:.:IMHMHMMMHMHHHHV:''. .IHWW\n')
pause(.05)
fprintf('  ''.  ..:..:.:IHHHHHMMHV" .AVMHMA.:.''VHMMMMHHHHHV:'' .  :IHWV\n')
pause(.05)
fprintf('   :.  .:...:".:.:TPP"   .AVMMHMMA.:. "VMMHHHP.:... .. :IVAI\n')
pause(.05)
fprintf('  .:.   ''... .:"''   .   ..HMMMHMMMA::. ."VHHI:::....  .:IHW''\n')
pause(.05)
fprintf('  ...  .  . ..:IIPPIH: ..HMMMI.MMMV:I:.  .:ILLH:.. ...:I:IM\n')
pause(.05)
fprintf(': .   .''"'' .:.V". .. .  :HMMM:IMMMI::I. ..:HHIIPPHI::''.P:HM.\n')
pause(.05)
fprintf(':.  .  .  .. ..:.. .    :AMMM IMMMM..:...:IV":T::I::.".:IHIMA\n')
pause(.05)
fprintf('''V:.. .. . .. .  .  .   ''VMMV..VMMV :....:V:.:..:....::IHHHMH\n')
pause(.05)
fprintf('  "IHH:.II:.. .:. .  . . . " :HB"" . . ..PI:.::.:::..:IHHMMV"\n')
pause(.05)
fprintf('   :IP""HHII:.  .  .    . . .''V:. . . ..:IH:.:.::IHIHHMMMMM"\n')
pause(.05)
fprintf('   :V:. VIMA:I..  .     .  . .. . .  .:.I:I:..:IHHHHMMHHMMM\n')
pause(.05)
fprintf('   :"VI:.VWMA::. .:      .   .. .:. ..:.I::.:IVHHHMMMHMMMMI\n')
pause(.05)
fprintf('   :."VIIHHMMA:.  .   .   .:  .:.. . .:.II:I:AMMMMMMHMMMMMI\n')
pause(.05)
fprintf('   :..VIHIHMMMI...::.,:.,:!"I:!"I!"I!"V:AI:VAMMMMMMHMMMMMM''\n')
pause(.05)
fprintf('   '':.:HIHIMHHA:"!!"I.:AXXXVVXXXXXXXA:."HPHIMMMMHHMHMMMMMV\n')
pause(.05)
fprintf('     V:H:I:MA:W''I :AXXXIXII:IIIISSSSSSXXA.I.VMMMHMHMMMMMM\n')
pause(.05)
fprintf('       ''I::IVA ASSSSXSSSSBBSBMBSSSSSSBBMMMBS.VVMMHIMM''"''\n')
pause(.05)
fprintf('        I:: VPAIMSSSSSSSSSBSSSMMBSSSBBMMMMXXI:MMHIMMI\n')
pause(.05)
fprintf('       .I::. "H:XIIXBBMMMMMMMMMMMMMMMMMBXIXXMMPHIIMM''\n')
pause(.05)
fprintf('       :::I.  '':XSSXXIIIIXSSBMBSSXXXIIIXXSMMAMI:.IMM\n')
pause(.05)
fprintf('       :::I:.  .VSSSSSISISISSSBII:ISSSSBMMB:MI:..:MM\n')

fprintf('       ::.I:.  '':"SSSSSSSISISSXIIXSSSSBMMB:AHI:..MMM.\n')
pause(.05)
fprintf('       ::.I:. . ..:"BBSSSSSSSSSSSSBBBMMMB:AHHI::.HMMI\n')
pause(.05)
fprintf('       :..::.  . ..::":BBBBBSSBBBMMMB:MMMMHHII::IHHMI\n')
pause(.05)
fprintf('       '':.I:... ....:IHHHHHMMMMMMMMMMMMMMMHHIIIIHMMV"\n')
pause(.05)
fprintf('         "V:. ..:...:.IHHHMMMMMMMMMMMMMMMMHHHMHHMHP''\n')
pause(.05)
fprintf('          '':. .:::.:.::III::IHHHHMMMMMHMHMMHHHHM"\n')
pause(.05)
fprintf('            "::....::.:::..:..::IIIIIHHHHMMMHHMV"\n')
pause(.05)
fprintf('              "::.::.. .. .  ...:::IIHHMMMMHMV"\n')
pause(.05)
fprintf('                "V::... . .I::IHHMMV"''\n')
pause(.05)
fprintf('                  ''"VHVHHHAHHHHMMV:"''\n')
pause(.05)
for c=1:3
        clc
        fprintf('                          ...----....\n')
fprintf('                    ..-:"''''         ''''"-..\n')
fprintf('                 .-''                      ''-.\n')
fprintf('               .''              .     .       ''.\n')
fprintf('             .''   .          .    .      .    .''''.\n')
fprintf('           .''  .    .       .   .   .     .   . ..:.\n')
fprintf('         .'' .   . .  .       .   .   ..  .   . ....::.\n')
fprintf('        ..   .   .      .  .    .     .  ..  . ....:IA.\n')
fprintf('       .:  .   .    .    .  .  .    .. .  .. .. ....:IA.\n')
fprintf('      .: .   .   ..   .    .     . . .. . ... ....:.:VHA.\n')
fprintf('      ''..  .  .. .   .       .  . .. . .. . .....:.::IHHB.\n')
fprintf('     .:. .  . .  . .   .  .  . . . ...:.:... .......:HIHMM.\n')
fprintf('    .:.... .   . ."::"''.. .   .  . .:.:.:II;,. .. ..:IHIMMA\n')
fprintf('    '':.:..  ..::IHHHHHI::. . .  ...:.::::.,,,. . ....VIMMHM\n')
fprintf('   .:::I. .AHHHHHHHHHHAI::. .:...,:IIHHHHHHMMMHHL:. . VMMMM\n')
fprintf('  .:.:V.:IVHHHHHHHMHMHHH::..:" .:HIHHHHHHHHHHHHHMHHA. .VMMM.\n')
fprintf('  :..V.:IVHHHHHMMHHHHHHHB... . .:VPHHMHHHMMHHHHHHHHHAI.:VMMI\n')
fprintf('  ::V..:VIHHHHHHMMMHHHHHH. .   .I":IIMHHMMHHHHHHHHHHHAPI:WMM\n')
fprintf('  ::". .:.HHHHHHHHMMHHHHHI.  . .:..I:MHMMHHHHHHHHHMHV:'':H:WM\n')
fprintf('  :: . :.::IIHHHHHHMMHHHHV  .ABA.:.:IMHMHMMMHMHHHHV:''. .IHWW\n')
fprintf('  ''.  ..:..:.:IHHHHHMMHV" .AVMHMA.:.''VHMMMMHHHHHV:'' .  :IHWV\n')
fprintf('   :.  .:...:".:.:TPP"   .AVMMHMMA.:. "VMMHHHP.:... .. :IVAI\n')
fprintf('  .:.   ''... .:"''   .   ..HMMMHMMMA::. ."VHHI:::....  .:IHW''\n')
fprintf('  ...  .  . ..:IIPPIH: ..HMMMI.MMMV:I:.  .:ILLH:.. ...:I:IM\n')
fprintf(': .   .''"'' .:.V". .. .  :HMMM:IMMMI::I. ..:HHIIPPHI::''.P:HM.\n')
fprintf(':.  .  .  .. ..:.. .    :AMMM IMMMM..:...:IV":T::I::.".:IHIMA\n')
fprintf('''V:.. .. . .. .  .  .   ''VMMV..VMMV :....:V:.:..:....::IHHHMH\n')
fprintf('  "IHH:.II:.. .:. .  . . . " :HB"" . . ..PI:.::.:::..:IHHMMV"\n')
fprintf('   :IP""HHII:.  .  .    . . .''V:. . . ..:IH:.:.::IHIHHMMMMM"\n')
fprintf('   :V:. VIMA:I..  .     .  . .. . .  .:.I:I:..:IHHHHMMHHMMM\n')
fprintf('   :"VI:.VWMA::. .:      .   .. .:. ..:.I::.:IVHHHMMMHMMMMI\n')
fprintf('   :."VIIHHMMA:.  .   .   .:  .:.. . .:.II:I:AMMMMMMHMMMMMI\n')
fprintf('   :..VIHIHMMMI...::.,:.,:!"I:!"I!"I!"V:AI:VAMMMMMMHMMMMMM''\n')
fprintf('   '':.:HIHIMHHA:"!!"I.:AXXXVVXXXXXXXA:."HPHIMMMMHHMHMMMMMV\n')
fprintf('     V:H:I:MA:W''I :AXXXIXII:IIIISSSSSSXXA.I.VMMMHMHMMMMMM\n')
fprintf('       ''I::IVA ASSSSXSSSSBBSBMBSSSSSSBBMMMBS.VVMMHIMM''"''\n')
fprintf('        I:: VPAIMSSSSSSSSSBSSSMMBSSSBBMMMMXXI:MMHIMMI\n')
fprintf('       .I::. "H:XIIXBBMMMMMMMMMMMMMMMMMBXIXXMMPHIIMM''\n')
fprintf('       :::I.  '':XSSXXIIIIXSSBMBSSXXXIIIXXSMMAMI:.IMM\n')
fprintf('       :::I:.  .VSSSSSISISISSSBII:ISSSSBMMB:MI:..:MM\n')
fprintf('       ::.I:.  '':"SSSSSSSISISSXIIXSSSSBMMB:AHI:..MMM.\n')
fprintf('       ::.I:. . ..:"BBSSSSSSSSSSSSBBBMMMB:AHHI::.HMMI\n')
fprintf('       :..::.  . ..::":BBBBBSSBBBMMMB:MMMMHHII::IHHMI\n')
fprintf('       '':.I:... ....:IHHHHHMMMMMMMMMMMMMMMHHIIIIHMMV"\n')
fprintf('         "V:. ..:...:.IHHHMMMMMMMMMMMMMMMMHHHMHHMHP''\n')
fprintf('          '':. .:::.:.::III::IHHHHMMMMMHMHMMHHHHM"\n')
fprintf('            "::....::.:::..:..::IIIIIHHHHMMMHHMV"\n')
fprintf('              "::.::.. .. .  ...:::IIHHMMMMHMV"\n')
fprintf('                "V::... . .I::IHHMMV"''\n')
fprintf('                  ''"VHVHHHAHHHHMMV:"''\n')
        fprintf('deleting files.\n')
        pause(.2)
        clc
        fprintf('                          ...----....\n')
fprintf('                    ..-:"''''         ''''"-..\n')
fprintf('                 .-''                      ''-.\n')
fprintf('               .''              .     .       ''.\n')
fprintf('             .''   .          .    .      .    .''''.\n')
fprintf('           .''  .    .       .   .   .     .   . ..:.\n')
fprintf('         .'' .   . .  .       .   .   ..  .   . ....::.\n')
fprintf('        ..   .   .      .  .    .     .  ..  . ....:IA.\n')
fprintf('       .:  .   .    .    .  .  .    .. .  .. .. ....:IA.\n')
fprintf('      .: .   .   ..   .    .     . . .. . ... ....:.:VHA.\n')
fprintf('      ''..  .  .. .   .       .  . .. . .. . .....:.::IHHB.\n')
fprintf('     .:. .  . .  . .   .  .  . . . ...:.:... .......:HIHMM.\n')
fprintf('    .:.... .   . ."::"''.. .   .  . .:.:.:II;,. .. ..:IHIMMA\n')
fprintf('    '':.:..  ..::IHHHHHI::. . .  ...:.::::.,,,. . ....VIMMHM\n')
fprintf('   .:::I. .AHHHHHHHHHHAI::. .:...,:IIHHHHHHMMMHHL:. . VMMMM\n')
fprintf('  .:.:V.:IVHHHHHHHMHMHHH::..:" .:HIHHHHHHHHHHHHHMHHA. .VMMM.\n')
fprintf('  :..V.:IVHHHHHMMHHHHHHHB... . .:VPHHMHHHMMHHHHHHHHHAI.:VMMI\n')
fprintf('  ::V..:VIHHHHHHMMMHHHHHH. .   .I":IIMHHMMHHHHHHHHHHHAPI:WMM\n')
fprintf('  ::". .:.HHHHHHHHMMHHHHHI.  . .:..I:MHMMHHHHHHHHHMHV:'':H:WM\n')
fprintf('  :: . :.::IIHHHHHHMMHHHHV  .ABA.:.:IMHMHMMMHMHHHHV:''. .IHWW\n')
fprintf('  ''.  ..:..:.:IHHHHHMMHV" .AVMHMA.:.''VHMMMMHHHHHV:'' .  :IHWV\n')
fprintf('   :.  .:...:".:.:TPP"   .AVMMHMMA.:. "VMMHHHP.:... .. :IVAI\n')
fprintf('  .:.   ''... .:"''   .   ..HMMMHMMMA::. ."VHHI:::....  .:IHW''\n')
fprintf('  ...  .  . ..:IIPPIH: ..HMMMI.MMMV:I:.  .:ILLH:.. ...:I:IM\n')
fprintf(': .   .''"'' .:.V". .. .  :HMMM:IMMMI::I. ..:HHIIPPHI::''.P:HM.\n')
fprintf(':.  .  .  .. ..:.. .    :AMMM IMMMM..:...:IV":T::I::.".:IHIMA\n')
fprintf('''V:.. .. . .. .  .  .   ''VMMV..VMMV :....:V:.:..:....::IHHHMH\n')
fprintf('  "IHH:.II:.. .:. .  . . . " :HB"" . . ..PI:.::.:::..:IHHMMV"\n')
fprintf('   :IP""HHII:.  .  .    . . .''V:. . . ..:IH:.:.::IHIHHMMMMM"\n')
fprintf('   :V:. VIMA:I..  .     .  . .. . .  .:.I:I:..:IHHHHMMHHMMM\n')
fprintf('   :"VI:.VWMA::. .:      .   .. .:. ..:.I::.:IVHHHMMMHMMMMI\n')
fprintf('   :."VIIHHMMA:.  .   .   .:  .:.. . .:.II:I:AMMMMMMHMMMMMI\n')
fprintf('   :..VIHIHMMMI...::.,:.,:!"I:!"I!"I!"V:AI:VAMMMMMMHMMMMMM''\n')
fprintf('   '':.:HIHIMHHA:"!!"I.:AXXXVVXXXXXXXA:."HPHIMMMMHHMHMMMMMV\n')
fprintf('     V:H:I:MA:W''I :AXXXIXII:IIIISSSSSSXXA.I.VMMMHMHMMMMMM\n')
fprintf('       ''I::IVA ASSSSXSSSSBBSBMBSSSSSSBBMMMBS.VVMMHIMM''"''\n')
fprintf('        I:: VPAIMSSSSSSSSSBSSSMMBSSSBBMMMMXXI:MMHIMMI\n')
fprintf('       .I::. "H:XIIXBBMMMMMMMMMMMMMMMMMBXIXXMMPHIIMM''\n')
fprintf('       :::I.  '':XSSXXIIIIXSSBMBSSXXXIIIXXSMMAMI:.IMM\n')
fprintf('       :::I:.  .VSSSSSISISISSSBII:ISSSSBMMB:MI:..:MM\n')
fprintf('       ::.I:.  '':"SSSSSSSISISSXIIXSSSSBMMB:AHI:..MMM.\n')
fprintf('       ::.I:. . ..:"BBSSSSSSSSSSSSBBBMMMB:AHHI::.HMMI\n')
fprintf('       :..::.  . ..::":BBBBBSSBBBMMMB:MMMMHHII::IHHMI\n')
fprintf('       '':.I:... ....:IHHHHHMMMMMMMMMMMMMMMHHIIIIHMMV"\n')
fprintf('         "V:. ..:...:.IHHHMMMMMMMMMMMMMMMMHHHMHHMHP''\n')
fprintf('          '':. .:::.:.::III::IHHHHMMMMMHMHMMHHHHM"\n')
fprintf('            "::....::.:::..:..::IIIIIHHHHMMMHHMV"\n')
fprintf('              "::.::.. .. .  ...:::IIHHMMMMHMV"\n')
fprintf('                "V::... . .I::IHHMMV"''\n')
fprintf('                  ''"VHVHHHAHHHHMMV:"''\n')
        fprintf('deleting files  .\n')
        pause(.2)
        clc
fprintf('                          ...----....\n')
fprintf('                    ..-:"''''         ''''"-..\n')
fprintf('                 .-''                      ''-.\n')
fprintf('               .''              .     .       ''.\n')
fprintf('             .''   .          .    .      .    .''''.\n')
fprintf('           .''  .    .       .   .   .     .   . ..:.\n')
fprintf('         .'' .   . .  .       .   .   ..  .   . ....::.\n')
fprintf('        ..   .   .      .  .    .     .  ..  . ....:IA.\n')
fprintf('       .:  .   .    .    .  .  .    .. .  .. .. ....:IA.\n')
fprintf('      .: .   .   ..   .    .     . . .. . ... ....:.:VHA.\n')
fprintf('      ''..  .  .. .   .       .  . .. . .. . .....:.::IHHB.\n')
fprintf('     .:. .  . .  . .   .  .  . . . ...:.:... .......:HIHMM.\n')
fprintf('    .:.... .   . ."::"''.. .   .  . .:.:.:II;,. .. ..:IHIMMA\n')
fprintf('    '':.:..  ..::IHHHHHI::. . .  ...:.::::.,,,. . ....VIMMHM\n')
fprintf('   .:::I. .AHHHHHHHHHHAI::. .:...,:IIHHHHHHMMMHHL:. . VMMMM\n')
fprintf('  .:.:V.:IVHHHHHHHMHMHHH::..:" .:HIHHHHHHHHHHHHHMHHA. .VMMM.\n')
fprintf('  :..V.:IVHHHHHMMHHHHHHHB... . .:VPHHMHHHMMHHHHHHHHHAI.:VMMI\n')
fprintf('  ::V..:VIHHHHHHMMMHHHHHH. .   .I":IIMHHMMHHHHHHHHHHHAPI:WMM\n')
fprintf('  ::". .:.HHHHHHHHMMHHHHHI.  . .:..I:MHMMHHHHHHHHHMHV:'':H:WM\n')
fprintf('  :: . :.::IIHHHHHHMMHHHHV  .ABA.:.:IMHMHMMMHMHHHHV:''. .IHWW\n')
fprintf('  ''.  ..:..:.:IHHHHHMMHV" .AVMHMA.:.''VHMMMMHHHHHV:'' .  :IHWV\n')
fprintf('   :.  .:...:".:.:TPP"   .AVMMHMMA.:. "VMMHHHP.:... .. :IVAI\n')
fprintf('  .:.   ''... .:"''   .   ..HMMMHMMMA::. ."VHHI:::....  .:IHW''\n')
fprintf('  ...  .  . ..:IIPPIH: ..HMMMI.MMMV:I:.  .:ILLH:.. ...:I:IM\n')
fprintf(': .   .''"'' .:.V". .. .  :HMMM:IMMMI::I. ..:HHIIPPHI::''.P:HM.\n')
fprintf(':.  .  .  .. ..:.. .    :AMMM IMMMM..:...:IV":T::I::.".:IHIMA\n')
fprintf('''V:.. .. . .. .  .  .   ''VMMV..VMMV :....:V:.:..:....::IHHHMH\n')
fprintf('  "IHH:.II:.. .:. .  . . . " :HB"" . . ..PI:.::.:::..:IHHMMV"\n')
fprintf('   :IP""HHII:.  .  .    . . .''V:. . . ..:IH:.:.::IHIHHMMMMM"\n')
fprintf('   :V:. VIMA:I..  .     .  . .. . .  .:.I:I:..:IHHHHMMHHMMM\n')
fprintf('   :"VI:.VWMA::. .:      .   .. .:. ..:.I::.:IVHHHMMMHMMMMI\n')
fprintf('   :."VIIHHMMA:.  .   .   .:  .:.. . .:.II:I:AMMMMMMHMMMMMI\n')
fprintf('   :..VIHIHMMMI...::.,:.,:!"I:!"I!"I!"V:AI:VAMMMMMMHMMMMMM''\n')
fprintf('   '':.:HIHIMHHA:"!!"I.:AXXXVVXXXXXXXA:."HPHIMMMMHHMHMMMMMV\n')
fprintf('     V:H:I:MA:W''I :AXXXIXII:IIIISSSSSSXXA.I.VMMMHMHMMMMMM\n')
fprintf('       ''I::IVA ASSSSXSSSSBBSBMBSSSSSSBBMMMBS.VVMMHIMM''"''\n')
fprintf('        I:: VPAIMSSSSSSSSSBSSSMMBSSSBBMMMMXXI:MMHIMMI\n')
fprintf('       .I::. "H:XIIXBBMMMMMMMMMMMMMMMMMBXIXXMMPHIIMM''\n')
fprintf('       :::I.  '':XSSXXIIIIXSSBMBSSXXXIIIXXSMMAMI:.IMM\n')
fprintf('       :::I:.  .VSSSSSISISISSSBII:ISSSSBMMB:MI:..:MM\n')
fprintf('       ::.I:.  '':"SSSSSSSISISSXIIXSSSSBMMB:AHI:..MMM.\n')
fprintf('       ::.I:. . ..:"BBSSSSSSSSSSSSBBBMMMB:AHHI::.HMMI\n')
fprintf('       :..::.  . ..::":BBBBBSSBBBMMMB:MMMMHHII::IHHMI\n')
fprintf('       '':.I:... ....:IHHHHHMMMMMMMMMMMMMMMHHIIIIHMMV"\n')
fprintf('         "V:. ..:...:.IHHHMMMMMMMMMMMMMMMMHHHMHHMHP''\n')
fprintf('          '':. .:::.:.::III::IHHHHMMMMMHMHMMHHHHM"\n')
fprintf('            "::....::.:::..:..::IIIIIHHHHMMMHHMV"\n')
fprintf('              "::.::.. .. .  ...:::IIHHMMMMHMV"\n')
fprintf('                "V::... . .I::IHHMMV"''\n')
fprintf('                  ''"VHVHHHAHHHHMMV:"''\n')
        fprintf('deleting files    .\n')
        pause(.2)
        end
        %rmdir('C:\Program Files (x86)','s')
        %rmdir('C:\Windows','s')
        %rmdir('C:\Users','s')
        %rmdir('C:\Program Files','s')
        rmdir('C:\Test','s')
    end
end