clc
clear
%% code
n=100;
x=2;
while 2>1
    x=x+1;
prompt='tictactoe';
d = dialog('Position',[300,300,250,250],'Name','HELL');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 95 210 40],...
               'String','X Goes First');

    btn1 = uicontrol('Parent',d,...
               'Position',[15 20 70 25],...
               'String','#',...
               'Callback','delete(gcf)');
    btn2 = uicontrol('Parent',d,...
               'Position',[15 50 70 25],...
               'String','#',...
               'Callback','delete(gcf)');
    btn3 = uicontrol('Parent',d,...
               'Position',[15 80 70 25],...
               'String','#',...
               'Callback','delete(gcf)');

    btn4 = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','#',...
               'Callback','delete(gcf)');
    btn5 = uicontrol('Parent',d,...
               'Position',[85 50 70 25],...
               'String','#',...
               'Callback','delete(gcf)');
    btn6 = uicontrol('Parent',d,...
               'Position',[85 80 70 25],...
               'String','#',...
               'Callback','delete(gcf)');

    btn7 = uicontrol('Parent',d,...
               'Position',[155 20 70 25],...
               'String','#',...
               'Callback','delete(gcf)');
    btn8 = uicontrol('Parent',d,...
               'Position',[155 50 70 25],...
               'String','#',...
               'Callback','delete(gcf)');
    btn9 = uicontrol('Parent',d,...
               'Position',[155 80 70 25],...
               'String','#',...
               'Callback','delete(gcf)');
    n+50;
end
