clc;clear;
start=questdlg('Start?','Virus.exe','yes','no','no');
if ~(strcmpi(start,'yes'))
    error('good idea')
else
    k=1;
    for c=1:10 %00000000
        name=sprintf('skull%0.0f',k);
        diary(name)
        diary on
        fprintf('                                  ...----....\n                    ..-:"''''         ''''"-..\n                 .-''                      ''-.\n               .''              .     .       ''.\n             .''   .          .    .      .    .''''.\n           .''  .    .       .   .   .     .   . ..:.\n         .'' .   . .  .       .   .   ..  .   . ....::.\n        ..   .   .      .  .    .     .  ..  . ....:IA.\n       .:  .   .    .    .  .  .    .. .  .. .. ....:IA.\n      .: .   .   ..   .    .     . . .. . ... ....:.:VHA.\n      ''..  .  .. .   .       .  . .. . .. . .....:.::IHHB.\n     .:. .  . .  . .   .  .  . . . ...:.:... .......:HIHMM.\n    .:.... .   . ."::"''.. .   .  . .:.:.:II;,. .. ..:IHIMMA\n    '':.:..  ..::IHHHHHI::. . .  ...:.::::.,,,. . ....VIMMHM\n   .:::I. .AHHHHHHHHHHAI::. .:...,:IIHHHHHHMMMHHL:. . VMMMM\n  .:.:V.:IVHHHHHHHMHMHHH::..:" .:HIHHHHHHHHHHHHHMHHA. .VMMM.\n  :..V.:IVHHHHHMMHHHHHHHB... . .:VPHHMHHHMMHHHHHHHHHAI.:VMMI\n  ::V..:VIHHHHHHMMMHHHHHH. .   .I":IIMHHMMHHHHHHHHHHHAPI:WMM\n  ::". .:.HHHHHHHHMMHHHHHI.  . .:..I:MHMMHHHHHHHHHMHV:'':H:WM\n  :: . :.::IIHHHHHHMMHHHHV  .ABA.:.:IMHMHMMMHMHHHHV:''. .IHWW\n  ''.  ..:..:.:IHHHHHMMHV" .AVMHMA.:.''VHMMMMHHHHHV:'' .  :IHWV\n   :.  .:...:".:.:TPP"   .AVMMHMMA.:. "VMMHHHP.:... .. :IVAI\n  .:.   ''... .:"''   .   ..HMMMHMMMA::. ."VHHI:::....  .:IHW''\n  ...  .  . ..:IIPPIH: ..HMMMI.MMMV:I:.  .:ILLH:.. ...:I:IM\n: .   .''"'' .:.V". .. .  :HMMM:IMMMI::I. ..:HHIIPPHI::''.P:HM.\n:.  .  .  .. ..:.. .    :AMMM IMMMM..:...:IV":T::I::.".:IHIMA\n''V:.. .. . .. .  .  .   ''VMMV..VMMV :....:V:.:..:....::IHHHMH\n  "IHH:.II:.. .:. .  . . . " :HB"" . . ..PI:.::.:::..:IHHMMV"\n   :IP""HHII:.  .  .    . . .''V:. . . ..:IH:.:.::IHIHHMMMMM"\n   :V:. VIMA:I..  .     .  . .. . .  .:.I:I:..:IHHHHMMHHMMM\n   :"VI:.VWMA::. .:      .   .. .:. ..:.I::.:IVHHHMMMHMMMMI\n   :."VIIHHMMA:.  .   .   .:  .:.. . .:.II:I:AMMMMMMHMMMMMI\n   :..VIHIHMMMI...::.,:.,:!"I:!"I!"I!"V:AI:VAMMMMMMHMMMMMM''\n   '':.:HIHIMHHA:"!!"I.:AXXXVVXXXXXXXA:."HPHIMMMMHHMHMMMMMV\n     V:H:I:MA:W''I :AXXXIXII:IIIISSSSSSXXA.I.VMMMHMHMMMMMM\n       ''I::IVA ASSSSXSSSSBBSBMBSSSSSSBBMMMBS.VVMMHIMM''"''\n        I:: VPAIMSSSSSSSSSBSSSMMBSSSBBMMMMXXI:MMHIMMI\n       .I::. "H:XIIXBBMMMMMMMMMMMMMMMMMBXIXXMMPHIIMM''\n       :::I.  '':XSSXXIIIIXSSBMBSSXXXIIIXXSMMAMI:.IMM\n       :::I:.  .VSSSSSISISISSSBII:ISSSSBMMB:MI:..:MM\n       ::.I:.  '':"SSSSSSSISISSXIIXSSSSBMMB:AHI:..MMM.\n       ::.I:. . ..:"BBSSSSSSSSSSSSBBBMMMB:AHHI::.HMMI\n       :..::.  . ..::":BBBBBSSBBBMMMB:MMMMHHII::IHHMI\n       '':.I:... ....:IHHHHHMMMMMMMMMMMMMMMHHIIIIHMMV"\n         "V:. ..:...:.IHHHMMMMMMMMMMMMMMMMHHHMHHMHP''\n          '':. .:::.:.::III::IHHHHMMMMMHMHMMHHHHM"\n            "::....::.:::..:..::IIIIIHHHHMMMHHMV"\n              "::.::.. .. .  ...:::IIHHMMMMHMV"\n                "V::... . .I::IHHMMV"''\n                  ''"VHVHHHAHHHHMMV:"''\n''');
        diary off
        k=k+1;
    end
end
